/* eslint-disable prettier/prettier */
/* eslint-disable id-length */
import eosTexture from '@/atlas/assets/textures/eos.png';

export const MOONS = [
  {
    name: 'Eos',
    devName: 'Eos',
    id: 'p0',
    type: 'planet',
    color: '#234672',
    texture: eosTexture,
    position: { x: -8450000, y: 0, z: 0 },
    radius: 5500000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      "The primary planet of the solar system, Eos is a blue gas giant that marks the center of civilization.\n\nEos has an 11,000 kilometer diameter, the largest astroid belt in the system, and is home to the 'pringle' of Origin Stations.",
    namedBy: null,
    namedAt: null,
  },
  {
    name: 'Elysium',
    devName: 'Makar',
    id: 'm0',
    type: 'moon',
    color: '#D2B9BD',
    position: { x: -5168032.86, y: -20248930.39, z: 7764107.254 },
    radius: 245000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This moon was approximately placed using vector-distance approximation as outlined on this wiki page: https://github.com/Tmktahu/atlas/wiki/Moon-Coordinate-Approximation',
    namedBy: '[Collective] Hatman',
    namedAt: null,
  },
  {
    name: 'Chemosh',
    devName: 'Vello',
    id: 'm1',
    type: 'moon',
    color: '#8FA249',
    position: { x: -14249863.57, y: 7503214.358, z: 12746962.88 },
    radius: 200000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This moon was approximately placed using vector-distance approximation as outlined on this wiki page: https://github.com/Tmktahu/atlas/wiki/Moon-Coordinate-Approximation',
    namedBy: null,
    namedAt: null,
  },
  {
    name: 'Kumi',
    devName: 'Koilia',
    id: 'm2',
    type: 'moon',
    color: '#A98883',
    position: { x: -28873963.81, y: -31450146.3, z: 0 },
    radius: 245000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This moon is not properly placed on this map due to lack of measurements.\n\nIf you are interested in helping me map this moon on Atlas, DM me on discord at Fryke#0746',
    namedBy: '/u/WAYTOPOE',
    namedAt: '8/30/2021',
  },
  {
    name: 'Szellem',
    devName: 'Manes',
    id: 'm3',
    type: 'moon',
    color: '#99A3A5',
    position: { x: 17116140.89, y: 31571554.68, z: 0 },
    radius: 245000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This moon is not properly placed on this map due to lack of measurements.\n\nIf you are interested in helping me map this moon on Atlas, DM me on discord at Fryke#0746',
    namedBy: '[EPIC Corp] Rabir',
    namedAt: '8/18/2021',
  },
  {
    name: 'Albedo',
    devName: 'Albedo',
    id: 'm4',
    type: 'moon',
    color: '#D4B2A8',
    position: { x: -49433311.56, y: 24625257.96, z: 0 },
    radius: 245000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This moon is not properly placed on this map due to lack of measurements.\n\nIf you are interested in helping me map this moon on Atlas, DM me on discord at Fryke#0746',
    namedBy: '[AA] Diez, Laiskiainen, and KuiK',
    namedAt: '8/24/2021',
  },
  {
    name: 'Mare',
    devName: 'Hemera',
    id: 'm5',
    type: 'moon',
    color: '#4C6A8C',
    position: { x: 44776982.41, y: -5488560.406, z: 18387838.96 },
    radius: 245000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This moon was approximately placed using vector-distance approximation as outlined on this wiki page: https://github.com/Tmktahu/atlas/wiki/Moon-Coordinate-Approximation',
    namedBy: '[EPIC Corp] Subaru',
    namedAt: '8/13/2021',
  },
  {
    name: 'Alstel',
    devName: 'Antron',
    id: 'm6',
    type: 'moon',
    color: '#9C714E',
    position: { x: -5446398.94, y: -57769249.09, z: 9948573.683 },
    radius: 245000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This moon was approximately placed using vector-distance approximation as outlined on this wiki page: https://github.com/Tmktahu/atlas/wiki/Moon-Coordinate-Approximation',
    namedBy: 'Zz',
    namedAt: '9/13/2021',
  },
  {
    name: 'Masser',
    devName: 'Adamas',
    id: 'm7',
    type: 'moon',
    color: '#A32F30',
    position: { x: -71519222.21, y: -15724923.21, z: 0 },
    radius: 245000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This moon is not properly placed on this map due to lack of measurements.\n\nIf you are interested in helping me map this moon on Atlas, DM me on discord at Fryke#0746',
    namedBy: '[EPIC Corp] Nihil',
    namedAt: '10/9/2021',
  },
  {
    name: 'Caecus',
    devName: 'Caecus',
    id: 'm8',
    type: 'moon',
    color: '#457F45',
    position: { x: -14765947.52, y: 65836661.11, z: 7491245.483 },
    radius: 245000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This moon was approximately placed using vector-distance approximation as outlined on this wiki page: https://github.com/Tmktahu/atlas/wiki/Moon-Coordinate-Approximation',
    namedBy: '[EPIC Corp] Senkii',
    namedAt: '8/21/2021',
  },
  {
    name: 'Neso',
    devName: 'Nesokia',
    id: 'm9',
    type: 'moon',
    color: '#81307F',
    position: { x: -9623658.354, y: 66550929.39, z: 11630265.94 },
    radius: 245000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This moon was approximately placed using vector-distance approximation as outlined on this wiki page: https://github.com/Tmktahu/atlas/wiki/Moon-Coordinate-Approximation',
    namedBy: '[EPIC Corp] Senkii',
    namedAt: '8/23/2021',
  },
  {
    name: 'Aurora',
    devName: 'Knephas',
    id: 'm10',
    type: 'moon',
    color: '#7D8742',
    position: { x: 47644614.14, y: -49167022.64, z: -17508468.49 },
    radius: 245000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This moon was approximately placed using vector-distance approximation as outlined on this wiki page: https://github.com/Tmktahu/atlas/wiki/Moon-Coordinate-Approximation',
    namedBy: '[EPIC Corp] Alegost',
    namedAt: '8/21/2021',
  },
  {
    name: 'Amethyst',
    devName: 'Ostrum',
    id: 'm11',
    type: 'moon',
    color: '#68353A',
    position: { x: -33068924.46, y: -65362029.34, z: 27958942.65 },
    radius: 245000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This moon was approximately placed using vector-distance approximation as outlined on this wiki page: https://github.com/Tmktahu/atlas/wiki/Moon-Coordinate-Approximation',
    namedBy: '[EPIC Corp] Alegost',
    namedAt: '9/21/2021',
  },
  {
    name: 'Tartarus',
    devName: 'Chasma',
    id: 'm12',
    type: 'moon',
    color: '#D596B3',
    position: { x: 65753950.06, y: 34601870.18, z: 0 },
    radius: 245000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This moon is not properly placed on this map due to lack of measurements.\n\nIf you are interested in helping me map this moon on Atlas, DM me on discord at Fryke#0746',
    namedBy: '[EPIC Corp] Subaru',
    namedAt: '8/20/2021',
  },
  {
    name: 'Kypselis',
    devName: 'Melitta',
    id: 'm13',
    type: 'moon',
    color: '#507D7A',
    position: { x: -86816109.42, y: -59053099.15, z: 0 },
    radius: 245000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This moon is not properly placed on this map due to lack of measurements.\n\nIf you are interested in helping me map this moon on Atlas, DM me on discord at Fryke#0746',
    namedBy: '[B.E.E.S.] MrMunchkin21',
    namedAt: '9/18/2021',
  },
  {
    name: 'Magellan',
    devName: 'Charta',
    id: 'm14',
    type: 'moon',
    color: '#82C1CA',
    position: { x: -76910338.42, y: 69793635.71, z: -3702163.326 },
    radius: 245000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This moon was approximately placed using vector-distance approximation as outlined on this wiki page: https://github.com/Tmktahu/atlas/wiki/Moon-Coordinate-Approximation',
    namedBy: '[EPIC Corp] Nihil',
    namedAt: '9/15/2021',
  },
  {
    name: 'Iris',
    devName: 'Iris',
    id: 'm15',
    type: 'moon',
    color: '#C09E94',
    position: { x: 16765416.18, y: -120304655.9, z: -2675183.461 },
    radius: 245000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This moon was approximately placed using vector-distance approximation as outlined on this wiki page: https://github.com/Tmktahu/atlas/wiki/Moon-Coordinate-Approximation',
    namedBy: '[EPIC Corp] Alegost',
    namedAt: '9/1/2021',
  },
  {
    name: 'Szalonna',
    devName: 'Aether',
    id: 'm16',
    type: 'moon',
    color: '#AD2D2E',
    position: { x: 9525077.119, y: 139291017.3, z: -3964598.873 },
    radius: 245000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This moon was approximately placed using vector-distance approximation as outlined on this wiki page: https://github.com/Tmktahu/atlas/wiki/Moon-Coordinate-Approximation',
    namedBy: '[EPIC Corp] Rabir',
    namedAt: '8/31/2021',
  },
  {
    name: 'Ciel',
    devName: 'Ouranos',
    id: 'm17',
    type: 'moon',
    color: '#704A57',
    position: { x: 135310359.5, y: 34944284.77, z: 41338590.65 },
    radius: 245000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This moon was approximately placed using vector-distance approximation as outlined on this wiki page: https://github.com/Tmktahu/atlas/wiki/Moon-Coordinate-Approximation',
    namedBy: '[EPIC Corp] Subaru',
    namedAt: '8/27/2021',
  },
];

export const SUB_MOONS = [
  {
    name: 'Sugon',
    devName: 'Mox',
    id: 'm1-0',
    parentId: 'm1',
    type: 'sub_moon',
    color: '#8F8D78',
    positionOffset: { x: 1000000, y: 500000, z: 1000000 },
    radius: 100000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This satellite moon was approximately placed by eye based on in-game observations and screenshots. Chances are its position is not close enough to reality to rely on.\n\nIf you are interested in helping me map this moon on Atlas, DM me on discord at Fryke#0746',
    namedBy: 'Lanata',
    namedAt: null,
  },
  {
    name: 'Xevaos',
    devName: null,
    id: 'm2-0',
    parentId: 'm2',
    type: 'sub_moon',
    color: '#5A4A3D',
    positionOffset: { x: -1000000, y: 1000000, z: 100000 },
    radius: 100000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This satellite moon was approximately placed by eye based on in-game observations and screenshots. Chances are its position is not close enough to reality to rely on.\n\nIf you are interested in helping me map this moon on Atlas, DM me on discord at Fryke#0746',
    namedBy: 'supahffej',
    namedAt: null,
  },
  {
    name: 'AnaMllaan',
    devName: null,
    id: 'm2-1',
    parentId: 'm2',
    type: 'sub_moon',
    color: '#6C6549',
    positionOffset: { x: 1000000, y: -1500000, z: 500000 },
    radius: 100000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This satellite moon was approximately placed by eye based on in-game observations and screenshots. Chances are its position is not close enough to reality to rely on.\n\nIf you are interested in helping me map this moon on Atlas, DM me on discord at Fryke#0746',
    namedBy: 'supahffej',
    namedAt: null,
  },
  {
    name: 'Suti',
    devName: null,
    id: 'm3-0',
    parentId: 'm3',
    type: 'sub_moon',
    color: '#6C6A5D',
    positionOffset: { x: 1000000, y: 0, z: 0 },
    radius: 100000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This satellite moon was approximately placed by eye based on in-game observations and screenshots. Chances are its position is not close enough to reality to rely on.\n\nIf you are interested in helping me map this moon on Atlas, DM me on discord at Fryke#0746',
    namedBy: '[EPIC Corp] Rabir',
    namedAt: '8/18/2021',
  },
  {
    name: 'Aura',
    devName: null,
    id: 'm5-0',
    parentId: 'm5',
    type: 'sub_moon',
    color: '#C6CEA9',
    positionOffset: { x: 1000000, y: 0, z: 0 },
    radius: 100000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This satellite moon was approximately placed by eye based on in-game observations and screenshots. Chances are its position is not close enough to reality to rely on.\n\nIf you are interested in helping me map this moon on Atlas, DM me on discord at Fryke#0746',
    namedBy: '[EPIC Corp] Subaru',
    namedAt: '8/13/2021',
  },
  {
    name: 'Spud',
    devName: null,
    id: 'm6-0',
    parentId: 'm6',
    type: 'sub_moon',
    color: '#8F8D78',
    positionOffset: { x: 1000000, y: 0, z: 0 },
    radius: 100000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This satellite moon was approximately placed by eye based on in-game observations and screenshots. Chances are its position is not close enough to reality to rely on.\n\nIf you are interested in helping me map this moon on Atlas, DM me on discord at Fryke#0746',
    namedBy: 'Zz',
    namedAt: '9/13/2021',
  },
  {
    name: 'Secunda',
    devName: null,
    id: 'm7-0',
    parentId: 'm7',
    type: 'sub_moon',
    color: '#AA757B',
    positionOffset: { x: 1000000, y: 0, z: 0 },
    radius: 100000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This satellite moon was approximately placed by eye based on in-game observations and screenshots. Chances are its position is not close enough to reality to rely on.\n\nIf you are interested in helping me map this moon on Atlas, DM me on discord at Fryke#0746',
    namedBy: '[EPIC Corp] Nihil',
    namedAt: '10/9/2021',
  },
  {
    name: 'Mures',
    devName: null,
    id: 'm8-0',
    parentId: 'm8',
    type: 'sub_moon',
    color: '#8F8D78',
    positionOffset: { x: 1000000, y: 0, z: 0 },
    radius: 100000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This satellite moon was approximately placed by eye based on in-game observations and screenshots. Chances are its position is not close enough to reality to rely on.\n\nIf you are interested in helping me map this moon on Atlas, DM me on discord at Fryke#0746',
    namedBy: '[EPIC Corp] Senkii',
    namedAt: '8/21/2021',
  },
  {
    name: 'Ione',
    devName: null,
    id: 'm9-0',
    parentId: 'm9',
    type: 'sub_moon',
    color: '#9BAC4C',
    positionOffset: { x: 1000000, y: 0, z: 0 },
    radius: 100000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This satellite moon was approximately placed by eye based on in-game observations and screenshots. Chances are its position is not close enough to reality to rely on.\n\nIf you are interested in helping me map this moon on Atlas, DM me on discord at Fryke#0746',
    namedBy: '[EPIC Corp] Senkii',
    namedAt: '8/23/2021',
  },
  {
    name: 'Ferrum',
    devName: null,
    id: 'm11-0',
    parentId: 'm11',
    type: 'sub_moon',
    color: '#BE6E7B',
    positionOffset: { x: 1000000, y: 0, z: 0 },
    radius: 100000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This satellite moon was approximately placed by eye based on in-game observations and screenshots. Chances are its position is not close enough to reality to rely on.\n\nIf you are interested in helping me map this moon on Atlas, DM me on discord at Fryke#0746',
    namedBy: '[EPIC Corp] Alegost',
    namedAt: '9/21/2021',
  },
  {
    name: 'Tephra',
    devName: null,
    id: 'm12-0',
    parentId: 'm12',
    type: 'sub_moon',
    color: '#7D7455',
    positionOffset: { x: 1000000, y: 0, z: 0 },
    radius: 100000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This satellite moon was approximately placed by eye based on in-game observations and screenshots. Chances are its position is not close enough to reality to rely on.\n\nIf you are interested in helping me map this moon on Atlas, DM me on discord at Fryke#0746',
    namedBy: '[EPIC Corp] Subaru',
    namedAt: '8/20/2021',
  },
  {
    name: 'Mel',
    devName: null,
    id: 'm13-0',
    parentId: 'm13',
    type: 'sub_moon',
    color: '#7D2674',
    positionOffset: { x: 1000000, y: 0, z: 0 },
    radius: 100000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This satellite moon was approximately placed by eye based on in-game observations and screenshots. Chances are its position is not close enough to reality to rely on.\n\nIf you are interested in helping me map this moon on Atlas, DM me on discord at Fryke#0746',
    namedBy: '[B.E.E.S.] MrMunchkin21',
    namedAt: '9/18/2021',
  },
  {
    name: 'Borealis',
    devName: null,
    id: 'm15-0',
    parentId: 'm15',
    type: 'sub_moon',
    color: '#6F6B62',
    positionOffset: { x: 1000000, y: 0, z: 0 },
    radius: 100000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This satellite moon was approximately placed by eye based on in-game observations and screenshots. Chances are its position is not close enough to reality to rely on.\n\nIf you are interested in helping me map this moon on Atlas, DM me on discord at Fryke#0746',
    namedBy: '[EPIC Corp] Alegost',
    namedAt: '9/1/2021',
  },
  {
    name: 'Vilous',
    devName: null,
    id: 'm17-0',
    parentId: 'm17',
    type: 'sub_moon',
    color: '#7198A9',
    positionOffset: { x: 1000000, y: 0, z: 0 },
    radius: 100000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This satellite moon was approximately placed by eye based on in-game observations and screenshots. Chances are its position is not close enough to reality to rely on.\n\nIf you are interested in helping me map this moon on Atlas, DM me on discord at Fryke#0746',
    namedBy: '[EPIC Corp] Subaru',
    namedAt: '8/27/2021',
  },
  {
    name: 'Cassini',
    devName: null,
    id: 'm17-1',
    parentId: 'm17',
    type: 'sub_moon',
    color: '#8F8763',
    positionOffset: { x: 0, y: 1000000, z: 0 },
    radius: 100000,
    widthSegments: 50,
    heightSegments: 50,
    opacity: 0.9,
    description:
      'This satellite moon was approximately placed by eye based on in-game observations and screenshots. Chances are its position is not close enough to reality to rely on.\n\nIf you are interested in helping me map this moon on Atlas, DM me on discord at Fryke#0746',
    namedBy: '[EPIC Corp] Subaru',
    namedAt: '8/27/2021',
  },
];

export const ORBIT_RINGS = [
  { name: 'Elysium Orbit', radius: 22000000, color: '#FFFFFF' },
  { name: 'Chemosh Orbit', radius: 20000000, color: '#FFFFFF' },
  { name: 'Kumi Orbit', radius: 37500000, color: '#FFFFFF' },
  { name: 'Szellem Orbit', radius: 40625000, color: '#FFFFFF' },
  { name: 'Albedo Orbit', radius: 47812500, color: '#FFFFFF' },
  { name: 'Mare Orbit', radius: 48347500, color: '#FFFFFF' },
  { name: 'Alstel Orbit', radius: 58750000, color: '#FFFFFF' },
  { name: 'Masser Orbit', radius: 65000000, color: '#FFFFFF' },
  { name: 'Caecus Orbit', radius: 67812500, color: '#FFFFFF' },
  { name: 'Neso Orbit', radius: 68125000, color: '#FFFFFF' },
  { name: 'Aurora Orbit', radius: 70937500, color: '#FFFFFF' },
  { name: 'Amethyst Orbit', radius: 78125000, color: '#FFFFFF' },
  { name: 'Tartarus Orbit', radius: 81875000, color: '#FFFFFF' },
  { name: 'Kypselis Orbit', radius: 98125000, color: '#FFFFFF' },
  { name: 'Magellan Orbit', radius: 104062500, color: '#FFFFFF' },
  { name: 'Iris Orbit', radius: 121562500, color: '#FFFFFF' },
  { name: 'Szalonna Orbit', radius: 140625000, color: '#FFFFFF' },
  { name: 'Ciel Orbit', radius: 145500000, color: '#FFFFFF' },
];

export const ASTROID_BELTS = [
  {
    name: 'Eos Belt',
    type: 'belt',
    moonId: 'p0',
    color: '#2c809b',
    position: { x: -8450000, y: 0, z: 0 },
    overalRadius: 2608683.79425,
    innerRadius: 300000,
    radialSegments: 100,
    tubularSegments: 200,
    scaleX: 3.6666,
    scaleY: 3.6666,
    opacity: 0.5,
  },
  {
    name: 'Elysium Belt',
    type: 'belt',
    moonId: 'm0',
    color: '#459474',
    position: { x: -5008441.769, y: -21729143.49, z: 0 },
    overalRadius: 220000,
    innerRadius: 40000,
    radialSegments: 100,
    tubularSegments: 200,
    scaleX: 2,
    scaleY: 2,
    opacity: 0.5,
  },
  {
    name: 'Chemosh Belt',
    type: 'belt',
    moonId: 'm1',
    color: '#981300',
    position: { x: -21571180.58, y: 15094191.6, z: 0 },
    overalRadius: 220000,
    innerRadius: 40000,
    radialSegments: 100,
    tubularSegments: 200,
    scaleX: 2,
    scaleY: 2,
    opacity: 0.5,
  },
  {
    name: 'Kumi Belt',
    type: 'belt',
    moonId: 'm2',
    color: '#A05400',
    position: { x: -28873963.81, y: -31450146.3, z: 0 },
    overalRadius: 220000,
    innerRadius: 40000,
    radialSegments: 100,
    tubularSegments: 200,
    scaleX: 2,
    scaleY: 2,
    opacity: 0.5,
  },
  {
    name: 'Szellem Belt',
    type: 'belt',
    moonId: 'm3',
    color: '#FCAFDB',
    position: { x: 17116140.89, y: 31571554.68, z: 0 },
    overalRadius: 220000,
    innerRadius: 40000,
    radialSegments: 100,
    tubularSegments: 200,
    scaleX: 2,
    scaleY: 2,
    opacity: 0.5,
  },
  {
    name: 'Alstel Belt',
    type: 'belt',
    moonId: 'm6',
    color: '#C55CFF',
    position: { x: -3840528.126, y: -58568893.36, z: 0 },
    overalRadius: 220000,
    innerRadius: 40000,
    radialSegments: 100,
    tubularSegments: 200,
    scaleX: 2,
    scaleY: 2,
    opacity: 0.5,
  },
];

export const EOS_BELT_ZONES = [
  {
    name: 'Eos Belt Zone 5',
    moonId: 'p0',
    color: '#931fff',
    position: { x: -8450000, y: 0, z: 0 },
    overalRadius: 2608683.79425,
    innerRadius: 27272.72727,
    radialSegments: 100,
    tubularSegments: 200,
    scaleX: 3.6666,
    scaleY: 3.6666,
    opacity: 0.5,
  },
  {
    name: 'Eos Belt Zone 4',
    moonId: 'p0',
    color: '#ff2121',
    position: { x: -8450000, y: 0, z: 0 },
    overalRadius: 2608683.79425,
    innerRadius: 122727.272727272,
    radialSegments: 100,
    tubularSegments: 200,
    scaleX: 3.6666,
    scaleY: 3.6666,
    opacity: 0.5,
  },
  {
    name: 'Eos Belt Zone 3',
    moonId: 'p0',
    color: '#ff902e',
    position: { x: -8450000, y: 0, z: 0 },
    overalRadius: 2608683.79425,
    innerRadius: 204545.454545454,
    radialSegments: 100,
    tubularSegments: 200,
    scaleX: 3.6666,
    scaleY: 3.6666,
    opacity: 0.5,
  },
  {
    name: 'Eos Belt Zone 2',
    moonId: 'p0',
    color: '#2e74ff',
    position: { x: -8450000, y: 0, z: 0 },
    overalRadius: 2608683.79425,
    innerRadius: 286363.636363636,
    radialSegments: 100,
    tubularSegments: 200,
    scaleX: 3.6666,
    scaleY: 3.6666,
    opacity: 0.5,
  },
  {
    name: 'Eos Belt Zone 1',
    moonId: 'p0',
    color: '#2eff66',
    position: { x: -8450000, y: 0, z: 0 },
    overalRadius: 2608683.79425,
    innerRadius: 300000,
    radialSegments: 100,
    tubularSegments: 200,
    scaleX: 3.6666,
    scaleY: 3.6666,
    opacity: 0.5,
  },
];
