/* eslint-disable prettier/prettier */
/* eslint-disable id-length */

export const ORIGIN_STATIONS = [
  { name: 'Origin Station 1', type: 'origin_station', color: 'lime', position: { x: 30000, y: -5000, z: -60000 }, id: 'origin_station_1', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 2', type: 'origin_station', color: 'lime', position: { x: 25000, y: -15000, z: -55000 }, id: 'origin_station_2', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 3', type: 'origin_station', color: 'lime', position: { x: 25000, y: -25000, z: -50000 }, id: 'origin_station_3', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 4', type: 'origin_station', color: 'lime', position: { x: 20000, y: -35000, z: -40000 }, id: 'origin_station_4', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 5', type: 'origin_station', color: 'lime', position: { x: 15000, y: -40000, z: -30000 }, id: 'origin_station_5', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 6', type: 'origin_station', color: 'lime', position: { x: 10000, y: -45000, z: -20000 }, id: 'origin_station_6', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 7', type: 'origin_station', color: 'lime', position: { x: 10000, y: -50000, z: -10000 }, id: 'origin_station_7', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 8', type: 'origin_station', color: 'lime', position: { x: 10000, y: -50100, z: 0 }, id: 'origin_station_8', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 9', type: 'origin_station', color: 'lime', position: { x: 10000, y: -50000, z: 10000 }, id: 'origin_station_9', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 10', type: 'origin_station', color: 'lime', position: { x: 10000, y: -45000, z: 20000 }, id: 'origin_station_10', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 11', type: 'origin_station', color: 'lime', position: { x: 15000, y: -40000, z: 30000 }, id: 'origin_station_11', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 12', type: 'origin_station', color: 'lime', position: { x: 20000, y: -35000, z: 40000 }, id: 'origin_station_12', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 13', type: 'origin_station', color: 'lime', position: { x: 25000, y: -25000, z: 50000 }, id: 'origin_station_13', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 14', type: 'origin_station', color: 'lime', position: { x: 25000, y: -15000, z: 55000 }, id: 'origin_station_14', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 15', type: 'origin_station', color: 'lime', position: { x: 30000, y: -5000, z: 60000 }, id: 'origin_station_15', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 16', type: 'origin_station', color: 'lime', position: { x: 30000, y: 5000, z: 60000 }, id: 'origin_station_16', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 17', type: 'origin_station', color: 'lime', position: { x: 25000, y: 15000, z: 55000 }, id: 'origin_station_17', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 18', type: 'origin_station', color: 'lime', position: { x: 25000, y: 25000, z: 50000 }, id: 'origin_station_18', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 19', type: 'origin_station', color: 'lime', position: { x: 20000, y: 35000, z: 40000 }, id: 'origin_station_19', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 20', type: 'origin_station', color: 'lime', position: { x: 15000, y: 40000, z: 30000 }, id: 'origin_station_20', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 21', type: 'origin_station', color: 'lime', position: { x: 10000, y: 45000, z: 20000 }, id: 'origin_station_21', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 22', type: 'origin_station', color: 'lime', position: { x: 10000, y: 50000, z: 10000 }, id: 'origin_station_22', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 23', type: 'origin_station', color: 'lime', position: { x: 10000, y: 50000, z: 0 }, id: 'origin_station_23', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 24', type: 'origin_station', color: 'lime', position: { x: 10000, y: 50000, z: -10000 }, id: 'origin_station_24', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 25', type: 'origin_station', color: 'lime', position: { x: 10000, y: 45000, z: -20000 }, id: 'origin_station_25', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 26', type: 'origin_station', color: 'lime', position: { x: 15000, y: 40000, z: -30000 }, id: 'origin_station_26', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 27', type: 'origin_station', color: 'lime', position: { x: 20000, y: 35000, z: -40000 }, id: 'origin_station_27', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 28', type: 'origin_station', color: 'lime', position: { x: 25000, y: 25000, z: -50000 }, id: 'origin_station_28', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 29', type: 'origin_station', color: 'lime', position: { x: 25000, y: 15000, z: -55000 }, id: 'origin_station_29', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
  { name: 'Origin Station 30', type: 'origin_station', color: 'lime', position: { x: 30000, y: 5000, z: -60000 }, id: 'origin_station_30', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is an origin station that is positioned around the Eos Warp Gate. It serves as a spawn location for new players and currently houses many ship shops and functional structures such as:\n- Ship Design structure\n- Refueling structures\n- Ore selling terminals and drop-off locations\n- Auction house' },
];

export const TRANSMITTER_STATIONS = [
  { name: 'North', type: 'transmitter_station', color: 'red', position: { x: 20000, y: 0, z: 65000 }, id: 'transmitter_station_north', hide: false, autoScale: false, icon: 'satellite', group: 'Eos', description: 'This is a transmitter station used by position systems such as IPS and ISAN to calculate 3D coordinates.' },
  { name: 'South', type: 'transmitter_station', color: 'white', position: { x: 35000, y: 0, z: -65000 }, id: 'transmitter_station_south', hide: false, autoScale: false, icon: 'satellite', group: 'Eos', description: 'This is a transmitter station used by position systems such as IPS and ISAN to calculate 3D coordinates.' },
  { name: 'East', type: 'transmitter_station', color: 'yellow', position: { x: -20000, y: -60000, z: 0 }, id: 'transmitter_station_east', hide: false, autoScale: false, icon: 'satellite', group: 'Eos', description: 'This is a transmitter station used by position systems such as IPS and ISAN to calculate 3D coordinates.' },
  { name: 'West', type: 'transmitter_station', color: 'purple', position: { x: -5000, y: 60000, z: 0 }, id: 'transmitter_station_west', hide: false, autoScale: false, icon: 'satellite', group: 'Eos', description: 'This is a transmitter station used by position systems such as IPS and ISAN to calculate 3D coordinates.' },
];

export const EOS_STATIONS = [
  { name: 'Ghost Station Relicta', type: 'ghost_station', color: 'orange', position: { x: 92000, y: -1000, z: -113000 }, id: 'ghost_station_relicta', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is a ghost station that is positioned underneath the Eos belt. It serves as beacon of sorts, guiding players towards the other stations positioned under and inside the belt.\nIt has no structures, exists outside the safezone, and is not aligned to the global grid in any noticeable way.' },
  { name: 'Ghost Station Nox', type: 'ghost_station', color: 'orange', position: { x: 201000, y: -10000, z: -170000 }, id: 'ghost_station_nox', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is a ghost station that is positioned underneath the Eos belt. It serves as beacon of sorts, guiding players towards the other stations positioned under and inside the belt.\nIt has no structures, exists outside the safezone, and is actually aligned to the global grid. This station could be used for manual ship orrientation and gyroscope recalibration.' },
  { name: 'Trading Station Marka', type: 'trading_station', color: 'orange', position: { x: 325000, y: 0, z: -150000 }, id: 'trading_station_marka', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is a trading station that is positioned inside the Eos belt. It serves as a location for deep-belt miners to sell their ore and purchase ships without needing to travel back to Origin.\nIt features its own 25km radius safezone, a variety of structures, and is actually aligned to the global grid. Not only could this station could be used for manual ship orrientation and gyroscope recalibration, but it is possible to spawn in a ship that is perfectly aligned to the global grid here.\nAn interesting note is that the station is not centered on the text transponder that advertises its position. Rather the station itself is about 1000m away from the transponder text.' },
  { name: 'PVP Station Robur', type: 'pvp_station', color: 'orange', position: { x: -45000, y: 0, z: 0 }, id: 'pvp_station_robur', hide: false, autoScale: false, icon: 'station1', group: 'Eos', description: 'This is a station that is positioned just outside the Eos safezone towards the planet. It serves as a location for pvp around a station that is close to Origin, letting pvpers get back into the fight quickly.\nIt has no structures or other functionally. It only serves as a kind of terrain for space combat.' },
];

export const EOS_GATES = [
  { name: 'Eos Farbelt Gate', type: 'gate', color: 'aqua', position: { x: 0, y: 0, z: 0 }, id: 'eos_farbelt_gate', hide: false, autoScale: true, icon: 'stargate', group: 'Eos', description: 'This is the Eos "Farbelt" Gate. It allows fast travel to a warp gate positioned on the far side of Eos.' },
];
